# create a self-signing issuer - this is so we can create a self-signed CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-issuer
  namespace: cert-manager
spec:
  selfSigned: {}

# create the actual CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: ${INGRESS_HOST}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 87600h # 10 years
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ca-secret
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "dynamicacme,enroll,nanomdm,smallstep"

# create an issuer for the CA
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-secret
