resources:
- ca.yaml
- deviceinventory.yaml
- dynamicacme.yaml
- enroll.yaml
- nanodep.yaml
- nanomdm.yaml
- smallstep.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: template
  namespace: smallstep
  files:
  - files/template.json
- name: init
  namespace: smallstep
  files:
  - files/init.sh
