apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-issuer
  namespace: cert-manager
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: mycoolmdm.stream
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 87600h # 10 years
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ca-secret
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "dynamicacme,nanomdm,smallstep"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-secret
