apiVersion: v1
kind: Namespace
metadata:
  name: enroll

# generate API secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: session-auth-key
  namespace: enroll
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password

---
apiVersion: v1
kind: Secret
metadata:
  name: session-enc-key
  namespace: enroll
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroll
  namespace: enroll
  labels:
    app: enroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enroll
  template:
    metadata:
      labels:
        app: enroll
    spec:
      volumes:
        - name: ca
          secret:
            secretName: ca-secret
            items:
            - key: ca.crt
              path: ca.crt
      containers:
      - name: enroll
        image: registry-internal.mycoolmdm.stream/enroll:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SESSION_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: session-auth-key
              key: password
        - name: SESSION_ENC_KEY
          valueFrom:
            secretKeyRef:
              name: session-enc-key
              key: password
        # allow requests that don't include signed machine info
        - name: ALLOW_NO_MACHINEINFO
          value: "true"

        - name: CA_PATH
          value: "/etc/enroll/ca.crt"
        - name: DYNAMIC_API_URL
          value: "https://dynamicacme.dynamicacme/api/key"
        - name: DYNAMIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: password

        - name: MDM_URL
          value: "https://mycoolmdm.stream/mdm"
        - name: APNS_TOPIC
          value: "com.apple.mgmt.External.Test"
        - name: ACME_DIRECTORY
          value: "https://mycoolmdm.stream/acme/acme/directory"
        volumeMounts:
        - name: "ca"
          mountPath: /etc/enroll

---
apiVersion: v1
kind: Service
metadata:
  name: enroll
  namespace: enroll
spec:
  selector:
    app: enroll
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: enroll
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd
spec:
  rules:
  - host: "mycoolmdm.stream"
    http:
      paths:
      - path: /mdm/enroll
        pathType: Prefix
        backend:
          service:
            name: enroll
            port:
              number: 80
  tls:
    - secretName: ingress-tls
      hosts:
        - mycoolmdm.stream
