apiVersion: v1
kind: Namespace
metadata:
  name: password-generator

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: password-generator
  namespace: kube-system
spec:
  chart: https://helm.mittwald.de/charts/kubernetes-secret-generator-3.4.1.tgz
  targetNamespace: password-generator
