apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: registry
spec:
  basicAuth:
    secret: basic-auth

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: registry
  namespace: kube-system
spec:
  chart: https://helm.twun.io/docker-registry-2.2.3.tgz
  targetNamespace: registry
  valuesContent: |-
    persistence:
      enabled: true
      deleteEnabled: true
      existingClaim: registry

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,registry-basic-auth@kubernetescrd
spec:
  rules:
  - host: "registry.mycoolmdm.stream"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-docker-registry
            port:
              number: 5000
  tls:
    - secretName: ingress-tls
      hosts:
        - registry.mycoolmdm.stream

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-internal-ingress
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,kube-system-internal-only@kubernetescrd
spec:
  rules:
  - host: "registry-internal.mycoolmdm.stream"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-docker-registry
            port:
              number: 5000
  tls:
    - secretName: ingress-tls
      hosts:
        - registry-internal.mycoolmdm.stream
