# create a registry password, put this in a separate file to avoid overwriting this password
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: basic-auth
  namespace: registry
  annotations:
    secret-generator.v1.mittwald.de/type: basic-auth
stringData:
  username: admin
  password: blank # will be replaced by secret generator
